### ISSUE TITLE
timelapse.getTimelapseCurrentTimeInSeconds() stutters

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/timemachine-viewer#4]
Calling timelapse.getTimelapseCurrentTimeInSeconds() every webGL frame (60hz) shows infrequent updating, e.g.:
frame 0: 0.027500033378601074
frame 1: 0.027500033378601074
frame 2: 0.027500033378601074
frame 3: 0.027500033378601074
frame 4: 0.048500001430511475
frame 5: 0.048500001430511475
frame 6: 0.048500001430511475
frame 7: 0.048500001430511475
frame 8: 0.048500001430511475
frame 9: 0.06925004720687866

Perhaps it should call videoset.getCurrentTime() instead?

**Comment by pdille** [comment]
Happened to be digging through this code and wanted to drop this comment.

timelapse.getCurrentTime() is what you want to use and does just that (calls videoset.getCurrentTime()). Heh, too many similar names here.

Not sure what the intention of timelapse.getTimelapseCurrentTimeInSeconds() was but it returns the internal timelapseCurrentTimeInSeconds variable which is updated every time 'sync' is called on the videoset.

What I believe is happening is that timelapseCurrentTimeInSeconds is tied to the video events, which are not fired consistently. You'll see this with the timeupdate event on videos. From the spec it says:

> The event frequency is dependent on the system load, but will be thrown between about 4Hz and 66Hz (assuming the event handlers don't take longer than 250ms to run).

timelapse.getCurrentTime(), which calls videoset.getCurrentTime(), will do its own time polling and so should be the preferred method for getting time.
